/*2. Създайте изглед, който за всяка агенция извежда името на клиента с най-много
резервации. Тествайте изгледa.*/

CREATE VIEW view_2
AS
SELECT DISTINCT CUSTOMERS.FNAME,CUSTOMERS.LNAME
FROM BOOKINGS JOIN AGENCIES ON BOOKINGS.AGENCY=AGENCIES.NAME JOIN CUSTOMERS ON BOOKINGS.CUSTOMER_ID=CUSTOMERS.ID
GROUP BY AGENCIES.NAME,CUSTOMERS.FNAME,CUSTOMERS.LNAME
HAVING COUNT(CUSTOMERS.ID) >= ALL (SELECT COUNT(CUSTOMERS.ID)
										FROM BOOKINGS JOIN AGENCIES AS A ON BOOKINGS.AGENCY=A.NAME JOIN CUSTOMERS ON BOOKINGS.CUSTOMER_ID=CUSTOMERS.ID
										WHERE AGENCIES.NAME=A.NAME
										GROUP BY A.NAME,CUSTOMERS.ID)