/*1. Създайте изглед, който извежда име на авиокомпания оператор на полета, номер на полет
и брой пътници, потвърдили резервация за този полет. Тествайте изгледa.*/

CREATE VIEW view_1
AS
SELECT AIRLINES.NAME,FLIGHTS.FNUMBER,COUNT(BOOKINGS.CUSTOMER_ID) AS confirmed_passangers
FROM FLIGHTS JOIN AIRLINES ON FLIGHTS.AIRLINE_OPERATOR=AIRLINES.CODE LEFT JOIN BOOKINGS ON BOOKINGS.AIRLINE_CODE=AIRLINES.CODE AND BOOKINGS.FLIGHT_NUMBER=FLIGHTS.FNUMBER
WHERE BOOKINGS.STATUS=1
GROUP BY FLIGHTS.FNUMBER,AIRLINES.NAME
