/*c) NULL или NOT NULL ограничение*/

ALTER TABLE Airline ALTER COLUMN name VARCHAR(50) NOT NULL
ALTER TABLE Airline ALTER COLUMN country VARCHAR(50) NOT NULL
ALTER TABLE Airport ALTER COLUMN name VARCHAR(50) NOT NULL
ALTER TABLE Airport ALTER COLUMN country VARCHAR(50) NOT NULL
ALTER TABLE Airport ALTER COLUMN city VARCHAR(50) NOT NULL
ALTER TABLE Airplane ALTER COLUMN seats INT NOT NULL
ALTER TABLE Airplane ALTER COLUMN type VARCHAR(50) NOT NULL
ALTER TABLE Airplane ALTER COLUMN year DATE NOT NULL
ALTER TABLE Flight ALTER COLUMN flight_time TIME NOT NULL
ALTER TABLE Flight ALTER COLUMN flight_duration INT NOT NULL
ALTER TABLE Customer ALTER COLUMN fname VARCHAR(50) NOT NULL
ALTER TABLE Customer ALTER COLUMN lname VARCHAR(50) NOT NULL
ALTER TABLE Customer ALTER COLUMN email VARCHAR(50) NOT NULL
ALTER TABLE Booking ALTER COLUMN booking_date DATE NOT NULL
ALTER TABLE Booking ALTER COLUMN flight_date DATE NOT NULL
ALTER TABLE Booking ALTER COLUMN price DECIMAL(9,2) NOT NULL
ALTER TABLE Booking ALTER COLUMN status INT NOT NULL