/*Напишете заявка, която извежда имената на актьорите, участвали във
филми на продуценти с най-големи нетни активи.*/

SELECT STARSIN.STARNAME,MOVIEEXEC.NETWORTH,MOVIE.TITLE
FROM STARSIN JOIN MOVIE ON STARSIN.MOVIETITLE = MOVIE.TITLE JOIN MOVIEEXEC ON MOVIEEXEC.CERT# = MOVIE.PRODUCERC#
WHERE MOVIEEXEC.NETWORTH >= ALL (SELECT MOVIEEXEC.NETWORTH
						FROM MOVIEEXEC)