/*Напишете заявка, която извежда имената на актьорите, които не са
участвали в нито един филм.*/

SELECT MOVIESTAR.NAME,MOVIE.TITLE
FROM MOVIE JOIN STARSIN ON STARSIN.MOVIETITLE = MOVIE.TITLE RIGHT JOIN MOVIESTAR ON STARSIN.STARNAME = MOVIESTAR.NAME
WHERE MOVIE.TITLE IS NULL