--Напишете заявка, която извежда имената на актрисите, които са също и
--продуценти с нетни активи над 10 милиона.

SELECT ACTRESSES.STARNAME
FROM MOVIEEXEC JOIN (SELECT STARSIN.STARNAME
				FROM STARSIN JOIN MOVIESTAR ON STARSIN.STARNAME = MOVIESTAR.NAME
				WHERE MOVIESTAR.GENDER='F') AS ACTRESSES ON MOVIEEXEC.NAME = ACTRESSES.STARNAME
WHERE MOVIEEXEC.NETWORTH > 1000000