/*6. Напишете заявка, която извежда имената на най-леките кораби с най-много
оръдия.*/

SELECT SHIPS.NAME,CLASSES.DISPLACEMENT,CLASSES.NUMGUNS
FROM CLASSES JOIN SHIPS ON CLASSES.CLASS=SHIPS.CLASS
WHERE CLASSES.DISPLACEMENT <= ALL (SELECT CLASSES.DISPLACEMENT FROM CLASSES)
